[package]
name = "benchair"
version = "0.1.0"
edition = "2024"

[dependencies]
p3-air = "0.6.1"
p3-baby-bear = "0.6.1"
p3-challenger = "0.6.1"
p3-commit = "0.6.1"
p3-dft = "0.6.1"
p3-field = "0.6.1"
p3-fri = "0.6.1"
p3-matrix = "0.6.1"
p3-merkle-tree = "0.6.1"
p3-poseidon2 = "0.6.1"
p3-symmetric = "0.6.1"
p3-uni-stark = "0.6.1"
rand = "0.10.2"
