#!/usr/bin/env python3
"""gen_airmats.py — emit the accurate-triple coefficient matrices as
Rust (num, den) tables for the mul-schedule AIR's preprocessed
columns: L, R are 48x16; P is 16x48 (SMS files store P as 16x48
directly). Fractions have denominators in {1,2,4}."""

def parse_sms(path):
    lines = [l.split() for l in open(path) if l.strip()]
    rows, cols = int(lines[0][0]), int(lines[0][1])
    m = [[(0, 1)] * cols for _ in range(rows)]
    for f in lines[1:]:
        i, j, v = int(f[0]), int(f[1]), f[2]
        if i == 0:
            break
        if "/" in v:
            n, d = v.split("/")
            m[i - 1][j - 1] = (int(n), int(d))
        else:
            m[i - 1][j - 1] = (int(v), 1)
    return rows, cols, m


def emit(name, rows, cols, m):
    out = [f"pub const {name}: [[(i32, u32); {cols}]; {rows}] = ["]
    for r in m:
        out.append("    [" + ", ".join(f"({n}, {d})" for (n, d) in r) + "],")
    out.append("];")
    return "\n".join(out)


D = "matmul/dps48/plinopt/data"
src = ["// AUTO-GENERATED by matmul/gen_airmats.py from the accurate SMS triple."]
for name, f in [("L284", "L"), ("R284", "R"), ("P284", "P")]:
    rows, cols, m = parse_sms(f"{D}/4x4x4_48_accurate_{f}.sms")
    src.append(emit(name, rows, cols, m))
    print(f"{name}: {rows}x{cols}")
open("matmul/benchair/src/mats284.rs", "w").write("\n".join(src) + "\n")
print("matmul/benchair/src/mats284.rs written")
