#!/usr/bin/env python3
"""Regenerate src/slp315.rs from the PLinOpt data-dir SLPs
(4x4x4_48_rational_{L,R,P}.slp, snapshot 2026-07-07). Reuses
shiftmin's expression parser; /2^k becomes fmul by INV2POW[k]."""
import sys
sys.path.insert(0, 'matmul/dps48')
from shiftmin import parse

HDR = '''// AUTO-GENERATED by matmul/gen_slp315.py from PLinOpt data-dir SLPs
// (snapshot 2026-07-07; checker-verified <104,4>+<75,1>+<110,21>).
'''

def emit_fn(name, slp_path, n_in, n_out):
    ops = parse(slp_path)
    lines = [f"pub fn {name}(inp: &[u64; {n_in}], out: &mut [u64; {n_out}]) {{"]
    defined = {f"i{i}": f"inp[{i}]" for i in range(n_in)}
    tmp = 0
    for nm, terms in ops:
        expr = None
        for (s, src, k) in terms:
            ref = defined[src]
            piece = ref
            if k > 0:
                piece = f"fmul({ref}, {2**k})"
            elif k < 0:
                piece = f"fmul({ref}, INV2POW[{-k}])"
            if expr is None:
                expr = piece if s > 0 else f"fneg({piece})"
            else:
                expr = f"fadd({expr}, {piece})" if s > 0 else f"fsub({expr}, {piece})"
        v = f"t{tmp}"; tmp += 1
        lines.append(f"    let {v} = {expr};")
        defined[nm] = v
        if nm.startswith("o"):
            lines.append(f"    out[{nm[1:]}] = {v};")
    lines.append("}")
    return "\n".join(lines)

src = HDR
D = "matmul/dps48/plinopt/data"
src += emit_fn("slp_l", f"{D}/4x4x4_48_rational_L.slp", 16, 48) + "\n\n"
src += emit_fn("slp_r", f"{D}/4x4x4_48_rational_R.slp", 16, 48) + "\n\n"
src += emit_fn("slp_p", f"{D}/4x4x4_48_rational_P.slp", 48, 16) + "\n"
open("src/slp315.rs", "w").write(src)
print("src/slp315.rs regenerated")
