#!/usr/bin/env python3
"""gen_msl.py — emit Metal Shading Language kernels for batched 4x4
BabyBear tile multiplication: tile_naive (64 mont muls in-thread) and
tile_284 (the accurate rank-48 SLP lowered to MSL — fifth target of
the same codegen family: u64, u32, blocks, NEON lanes, AIR
expressions, now GPU threads). Montgomery mul avoids 64-bit ints:
t = a*b as (mulhi, lo); m = lo*NP; t + m*P has low word 0 by
construction, so the carry into the high word is (lo != 0).
Halving works in any domain: (x + (x&1 ? P : 0)) >> 1.
Output: matmul/benchmetal/src/tiles.metal
"""
import sys

sys.path.insert(0, 'matmul/dps48')
from shiftmin import parse

D = "matmul/dps48/plinopt/data"
BASE = "4x4x4_48_accurate"

HDR = """// AUTO-GENERATED by matmul/gen_msl.py from the PLinOpt accurate
// triple (284 ops). BabyBear Montgomery arithmetic, 32-bit only.
#include <metal_stdlib>
using namespace metal;

constant uint P  = 0x78000001u;
constant uint NP = 0x77ffffffu; // -p^{-1} mod 2^32 (checked host-side)

inline uint mont_mul(uint a, uint b) {
    uint lo = a * b;
    uint hi = mulhi(a, b);
    uint m  = lo * NP;
    uint mp_hi = mulhi(m, P);
    // t + m*P: low 32 bits are 0 by construction; carry = (lo != 0)
    uint t2 = hi + mp_hi + (lo != 0u ? 1u : 0u);
    return t2 >= P ? t2 - P : t2;
}
inline uint badd(uint a, uint b) {
    uint s = a + b;
    return s >= P ? s - P : s;
}
inline uint bsub(uint a, uint b) {
    return a >= b ? a - b : a + P - b;
}
inline uint bneg(uint a) { return a == 0u ? 0u : P - a; }
inline uint bhalf(uint x) { return (x + ((x & 1u) ? P : 0u)) >> 1; }
"""


def emit_fn(name, slp_path, n_in, n_out):
    ops = parse(slp_path)
    lines = [f"inline void {name}(thread const uint* inp, thread uint* out) {{"]
    defined = {f"i{i}": f"inp[{i}]" for i in range(n_in)}
    defined["0"] = "0u"
    tmp = 0
    for nm, terms in ops:
        expr = None
        for (s, src, k) in terms:
            piece = defined[src]
            if k > 0:
                for _ in range(k):
                    piece = f"badd({piece}, {piece})"
            elif k < 0:
                for _ in range(-k):
                    piece = f"bhalf({piece})"
            if expr is None:
                expr = piece if s > 0 else f"bneg({piece})"
            else:
                expr = f"badd({expr}, {piece})" if s > 0 else f"bsub({expr}, {piece})"
        v = f"t{tmp}"
        tmp += 1
        lines.append(f"    uint {v} = {expr};")
        defined[nm] = v
        if nm.startswith("o"):
            lines.append(f"    out[{nm[1:]}] = {v};")
    lines.append("}")
    return "\n".join(lines)


def emit_naive_unrolled():
    """fully unrolled naive kernel body: constant indices only, so the
    compiler registerizes exactly like the generated SLP does — the
    fair control for the loop-indexed tile_naive."""
    lines = []
    for i in range(4):
        for j in range(4):
            terms = " , ".join(
                f"mont_mul(av[{i*4+k}], bv[{k*4+j}])" for k in range(4)
            ).split(" , ")
            e = terms[0]
            for t in terms[1:]:
                e = f"badd({e}, {t})"
            lines.append(f"    c[{i*4+j} * T + tid] = {e};")
    return "\n".join(lines)


KERNELS = """
// SoA layout: a[i*T + tid], b[i*T + tid], c[i*T + tid]
kernel void tile_naive(device const uint* a [[buffer(0)]],
                       device const uint* b [[buffer(1)]],
                       device uint* c [[buffer(2)]],
                       constant uint& T [[buffer(3)]],
                       uint tid [[thread_position_in_grid]]) {
    if (tid >= T) return;
    uint av[16], bv[16];
    for (uint i = 0; i < 16; i++) { av[i] = a[i * T + tid]; bv[i] = b[i * T + tid]; }
    for (uint i = 0; i < 4; i++)
        for (uint j = 0; j < 4; j++) {
            uint s = mont_mul(av[i * 4], bv[j]);
            for (uint k = 1; k < 4; k++)
                s = badd(s, mont_mul(av[i * 4 + k], bv[k * 4 + j]));
            c[(i * 4 + j) * T + tid] = s;
        }
}

kernel void tile_284(device const uint* a [[buffer(0)]],
                     device const uint* b [[buffer(1)]],
                     device uint* c [[buffer(2)]],
                     constant uint& T [[buffer(3)]],
                     uint tid [[thread_position_in_grid]]) {
    if (tid >= T) return;
    uint av[16], bv[16], la[48], rb[48], pr[48], cv[16];
    for (uint i = 0; i < 16; i++) { av[i] = a[i * T + tid]; bv[i] = b[i * T + tid]; }
    slp_l(av, la);
    slp_r(bv, rb);
    for (uint t = 0; t < 48; t++) pr[t] = mont_mul(la[t], rb[t]);
    slp_p(pr, cv);
    for (uint z = 0; z < 16; z++) c[z * T + tid] = cv[z];
}
"""

src = HDR
src += emit_fn("slp_l", f"{D}/{BASE}_L.slp", 16, 48) + "\n\n"
src += emit_fn("slp_r", f"{D}/{BASE}_R.slp", 16, 48) + "\n\n"
src += emit_fn("slp_p", f"{D}/{BASE}_P.slp", 48, 16) + "\n"
src += KERNELS
src += """
kernel void tile_naive_unrolled(device const uint* a [[buffer(0)]],
                                device const uint* b [[buffer(1)]],
                                device uint* c [[buffer(2)]],
                                constant uint& T [[buffer(3)]],
                                uint tid [[thread_position_in_grid]]) {
    if (tid >= T) return;
    uint av[16], bv[16];
    for (uint i = 0; i < 16; i++) { av[i] = a[i * T + tid]; bv[i] = b[i * T + tid]; }
""" + emit_naive_unrolled() + """
}
"""
open("matmul/benchmetal/src/tiles.metal", "w").write(src)
print("matmul/benchmetal/src/tiles.metal generated")
