#!/usr/bin/env python3
"""Regenerate Rust SLP modules from PLinOpt data-dir SLP triples.
Usage: gen_slp315.py [base] [outprefix]
  base       data-dir triple base name (default 4x4x4_48_rational)
  outprefix  src/<outprefix>.rs scalar + src/<outprefix>g.rs generic
Defaults regenerate the original slp315 pair; run with
  gen_slp315.py 4x4x4_48_accurate slp284
for the 284-op accurate triple (checker: <80,4>+<68,8>+<108,16>).
/2^k becomes fmul by INV2POW[k] (scalar) or scale2(-k) (generic).
Reuses shiftmin's expression parser."""
import sys

sys.path.insert(0, 'matmul/dps48')
from shiftmin import parse

BASE = sys.argv[1] if len(sys.argv) > 1 else "4x4x4_48_rational"
PRE = sys.argv[2] if len(sys.argv) > 2 else "slp315"
D = "matmul/dps48/plinopt/data"


def emit_scalar(name, slp_path, n_in, n_out):
    ops = parse(slp_path)
    lines = [f"pub fn {name}(inp: &[u64; {n_in}], out: &mut [u64; {n_out}]) {{"]
    defined = {f"i{i}": f"inp[{i}]" for i in range(n_in)}
    tmp = 0
    for nm, terms in ops:
        expr = None
        for (s, src, k) in terms:
            ref = defined[src]
            piece = ref
            if k > 0:
                piece = f"fmul({ref}, {2**k})"
            elif k < 0:
                piece = f"fmul({ref}, INV2POW[{-k}])"
            if expr is None:
                expr = piece if s > 0 else f"fneg({piece})"
            else:
                expr = f"fadd({expr}, {piece})" if s > 0 else f"fsub({expr}, {piece})"
        v = f"t{tmp}"
        tmp += 1
        lines.append(f"    let {v} = {expr};")
        defined[nm] = v
        if nm.startswith("o"):
            lines.append(f"    out[{nm[1:]}] = {v};")
    lines.append("}")
    return "\n".join(lines)


def emit_generic(name, slp_path, n_in, n_out):
    ops = parse(slp_path)
    lines = [f"pub fn {name}<T: El>(inp: &[T], out: &mut [T]) {{"]
    defined = {f"i{i}": f"inp[{i}]" for i in range(n_in)}
    tmp = 0
    for nm, terms in ops:
        expr = None
        for (s, src, k) in terms:
            ref = defined[src]
            piece = f"{ref}.scale2({k})" if k else None
            if expr is None:
                first = piece if piece else f"{ref}.clone()"
                expr = first if s > 0 else f"{first}.neg()"
            else:
                arg = piece if piece else ref
                op = "add" if s > 0 else "sub"
                expr = f"{expr}.{op}(&{arg})"
        v = f"t{tmp}"
        tmp += 1
        lines.append(f"    let {v} = {expr};")
        defined[nm] = v
        if nm.startswith("o"):
            lines.append(f"    out[{nm[1:]}] = {v}.clone();")
    lines.append("}")
    return "\n".join(lines)


hdr_s = f"""// AUTO-GENERATED by matmul/gen_slp315.py from PLinOpt data-dir SLPs
// (triple {BASE}).
"""
src = hdr_s
src += emit_scalar("slp_l", f"{D}/{BASE}_L.slp", 16, 48) + "\n\n"
src += emit_scalar("slp_r", f"{D}/{BASE}_R.slp", 16, 48) + "\n\n"
src += emit_scalar("slp_p", f"{D}/{BASE}_P.slp", 48, 16) + "\n"
open(f"src/{PRE}.rs", "w").write(src)

hdr_g = f"""// AUTO-GENERATED by matmul/gen_slp315.py (generic variant) from the
// PLinOpt data-dir SLP triple {BASE}. El is any Goldilocks-
// element-like type: u64 scalars or matrix blocks.
"""
src = hdr_g
src += emit_generic("gslp_l", f"{D}/{BASE}_L.slp", 16, 48) + "\n\n"
src += emit_generic("gslp_r", f"{D}/{BASE}_R.slp", 16, 48) + "\n\n"
src += emit_generic("gslp_p", f"{D}/{BASE}_P.slp", 48, 16) + "\n"
open(f"src/{PRE}g.rs", "w").write(src)
print(f"src/{PRE}.rs + src/{PRE}g.rs regenerated from {BASE}")
